config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("spam_mailing.urls", namespace="spam_mailing")),
    path("users/", include("users.urls", namespace="users")),
]

spam_mailing/urls.py
from django.urls import path

from spam_mailing.views import (HomeView, MailingAttemptView, MailingCreateView, MailingDeleteView, MailingDetailView,
                                MailingListView, MailingStopView, MailingUpdateView, MessageCreateView,
                                MessageDeleteView, MessageDetailView, MessageUpdateView, ReceiverCreateView,
                                ReceiverDeleteView, ReceiverDetailView, ReceiverListView, ReceiverUpdateView, SendMail,
                                UserListView)

app_name = "spam_mailing"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("spam_mailing/<int:pk>/", ReceiverDetailView.as_view(), name="receiver"),
    path("spam_mailing/create/", ReceiverCreateView.as_view(), name="receiver_create"),
    path("spam_mailing/<int:pk>/update/", ReceiverUpdateView.as_view(), name="receiver_update"),
    path("spam_mailing/<int:pk>/delete/", ReceiverDeleteView.as_view(), name="receiver_delete"),
    # path('category/<int:pk>/', cache_page(60)(ReceiverDetailView.as_view()), name='product_cache')
    path("message/<int:pk>/", MessageDetailView.as_view(), name="message"),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/send_mail/", SendMail.as_view(), name="send_mail"),
    path("mailing_attempt/", MailingAttemptView.as_view(), name="mailing_attempt"),
    path("list_view/", ReceiverListView.as_view(), name="list_view"),
    path("mailing_list/", MailingListView.as_view(), name="mailing_view"),
    path("mailing_stop/<int:pk>/", MailingStopView.as_view(), name="mailing_stop"),

    path("user_list/", UserListView.as_view(), name="user_list"),
]

users/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (EmailConfirmationFailedView, EmailConfirmationSentView, EmailConfirmedView, UserBanView,
                         UserBlock, UserConfirmEmailView, UserCreateView, UserForgotPasswordView,
                         UserPasswordResetConfirmView)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html", form_class=AuthenticationForm), name="login"),
    path("logout/", LogoutView.as_view(next_page="spam_mailing:home"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirmation-sent/", EmailConfirmationSentView.as_view(), name="email_confirmation_sent"),
    path("confirm-email/<str:uidb64>/<str:token>/", UserConfirmEmailView.as_view(), name="confirm_email"),
    # Подтверждение email
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path("confirm-email-failed/", EmailConfirmationFailedView.as_view(), name="email_confirmation_failed"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path("set-new-password/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user_ban", UserBanView.as_view(), name="user_ban"),
    path("user_block/<int:pk>/", UserBlock.as_view(), name="user_block"),
]

spam_mailing/models.py
from django.db import models

from users.models import CustomUser

# Create your models here.


class Receiver(models.Model):
    email = models.EmailField(verbose_name="email", unique=True)
    name = models.CharField(verbose_name="ФИО", null=True, blank=True)
    description = models.TextField(verbose_name="Описание", null=True, blank=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="владелец", null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Получатель рассылки"
        verbose_name_plural = "Получатели рассылки"
        permissions = [("can_view_reciever", "can_view_reciever")]


class Message(models.Model):
    text_topic = models.TextField(verbose_name="Текст письма", null=True, blank=True)
    text_body = models.CharField(verbose_name="Текст", null=True, blank=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="владелец", null=True, blank=True)

    def __str__(self):
        return f"{self.text_topic}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Mailing(models.Model):
    date_start = models.DateTimeField(verbose_name="Дата начала рассылки", null=True, blank=True)
    date_end = models.DateTimeField(verbose_name="Дата конца рассылки", null=True, blank=True)
    status = models.CharField(
        verbose_name="статус сообщения",
        choices=[("Создана", "Создана"), ("Завершена", "Завершена"), ("Запущена", "Запущена")],
    )
    text_msg = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Сообщение", related_name="message")
    receivers_msgs = models.ManyToManyField(Receiver, verbose_name="Получатели", related_name="receiver")
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="владелец", null=True, blank=True)

    def __str__(self):
        return f"{self.status_msg}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [("can_view_mailing", "can_view_mailing")]


class MailingAttempt(models.Model):
    date_attempt = models.DateTimeField(verbose_name="Дата и время попытки", null=True, blank=True)
    status = models.CharField(
        verbose_name="статус сообщения", choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")]
    )
    mail_response = models.TextField(verbose_name="Текст", null=True, blank=True)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Расслылка", related_name="mailing")
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="владелец", null=True, blank=True)

    def __str__(self):
        return f"{self.mailing}"

    class Meta:
        verbose_name = "Попытка расслыки"
        verbose_name_plural = "Попытки рассылки"

spam_mailing/forms.py
from django.forms import ModelForm

from spam_mailing.models import Mailing, Message, Receiver


class ReceiverForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReceiverForm, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs.update({"class": "form-control", "placeholder": "Введите email получателя"})
        self.fields["name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите ФИО получателя"})
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Дополнительная информация"}
        )

    class Meta:
        model = Receiver
        fields = "__all__"


class MessageForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        self.fields["text_topic"].widget.attrs.update({"class": "form-control", "placeholder": "Введите тему письма"})
        self.fields["text_body"].widget.attrs.update({"class": "form-control", "placeholder": "Введите текст письма"})

    class Meta:
        model = Message
        fields = "__all__"


class MailingForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)

        self.fields["date_start"].widget.attrs.update({"class": "form-control", "placeholder": "Введите тему письма"})
        self.fields["date_end"].widget.attrs.update({"class": "form-control", "placeholder": "Введите текст письма"})
        self.fields["status"].widget.attrs.update({"class": "form-control", "placeholder": "Введите текст письма"})
        self.fields["text_msg"].widget.attrs.update({"class": "form-control", "placeholder": "Введите текст письма"})
        self.fields["receivers_msgs"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите текст письма"}
        )

    class Meta:
        model = Mailing
        fields = "__all__"

spam_mailing/views.py
import smtplib

from django.core.exceptions import PermissionDenied
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from spam_mailing.forms import MailingForm, MessageForm, ReceiverForm
from spam_mailing.models import Mailing, MailingAttempt, Message, Receiver
from spam_mailing.services import send_mail_list
from users.models import CustomUser


@method_decorator(cache_page(60), name="dispatch")
class HomeView(ListView):
    model = Mailing
    template_name = "spam_mailing/home.html"
    context_object_name = "mailing"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["all_mailing"] = Mailing.objects.all()
        context["active_mailing"] = Mailing.objects.filter(status="Запущена")
        context["unique_receivers"] = Receiver.objects.all()
        return context


class ReceiverCreateView(CreateView):
    model = Receiver
    template_name = "spam_mailing/receiver_create.html"
    context_object_name = "receiver_create"
    form_class = ReceiverForm
    success_url = reverse_lazy("spam_mailing:home")

    def form_valid(self, form):
        receiver = form.save()
        user = self.request.user
        receiver.owner = user
        receiver.save()
        return super().form_valid(form)


class ReceiverListView(ListView):
    model = Receiver
    template_name = "spam_mailing/reciever_list.html"
    context_object_name = "receiver_list"

    def get_queryset(self):
        user = self.request.user
        if user.has_perm("spam_mailing.can_view_reciever"):
            return Receiver.objects.all()
        return Receiver.objects.filter(owner=self.request.user)


@method_decorator(cache_page(60), name="dispatch")
class ReceiverDetailView(DetailView):
    model = Receiver
    template_name = "spam_mailing/receiver_detail.html"
    context_object_name = "receiver_detail"

    def get_queryset(self):
        return Receiver.objects.filter(owner=self.request.user)


class ReceiverUpdateView(UpdateView):
    model = Receiver
    template_name = "spam_mailing/receiver_create.html"
    context_object_name = "receiver_update"
    form_class = ReceiverForm

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ReceiverForm
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse("spam_mailing:receiver", args=[self.kwargs.get("pk")])


class ReceiverDeleteView(DeleteView):
    model = Receiver
    template_name = "spam_mailing/receiver_delete.html"
    context_object_name = "receiver_delete"
    success_url = reverse_lazy("spam_mailing:home")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return super().get_form_class()
        else:
            raise PermissionDenied


class MessageCreateView(CreateView):
    model = Message
    template_name = "spam_mailing/message_create.html"
    context_object_name = "message_create"
    form_class = MessageForm
    success_url = reverse_lazy("spam_mailing:home")

    def form_valid(self, form):
        receiver = form.save()
        user = self.request.user
        receiver.owner = user
        receiver.save()
        return super().form_valid(form)


class MessageListView(ListView):
    model = Message
    template_name = "spam_mailing/message_list.html"
    context_object_name = "message_list"


class MessageDetailView(DetailView):
    model = Message
    template_name = "spam_mailing/message_detail.html"
    context_object_name = "message_detail"


class MessageUpdateView(UpdateView):
    model = Message
    template_name = "spam_mailing/message_create.html"
    context_object_name = "message_update"
    form_class = MessageForm

    def get_success_url(self):
        return reverse("spam_mailing:message", args=[self.kwargs.get("pk")])


class MessageDeleteView(DeleteView):
    model = Message
    template_name = "spam_mailing/message_delete.html"
    context_object_name = "message_delete"
    success_url = reverse_lazy("spam_mailing:home")


class MailingCreateView(CreateView):
    model = Mailing
    template_name = "spam_mailing/mailing_create.html"
    context_object_name = "mailing_create"
    form_class = MailingForm

    success_url = reverse_lazy("spam_mailing:home")

    def form_valid(self, form):
        receiver = form.save()
        user = self.request.user
        receiver.owner = user
        receiver.save()
        return super().form_valid(form)


class MailingListView(ListView):
    model = Mailing
    template_name = "spam_mailing/mailing_list.html"
    context_object_name = "mailing_list"

    def get_queryset(self):
        user = self.request.user
        if user.has_perm("spam_mailing.can_view_mailing"):
            return Mailing.objects.all()
        return Mailing.objects.filter(owner=self.request.user)


class MailingDetailView(DetailView):
    model = Mailing
    template_name = "spam_mailing/mailing_detail.html"
    context_object_name = "mailing_detail"


class MailingUpdateView(UpdateView):
    model = Mailing
    template_name = "spam_mailing/mailing_create.html"
    context_object_name = "mailing_update"
    form_class = MailingForm

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse("spam_mailing:mailing", args=[self.kwargs.get("pk")])


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = "spam_mailing/mailing_delete.html"
    context_object_name = "mailing_delete"
    success_url = reverse_lazy("spam_mailing:home")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return super().get_form_class()
        else:
            raise PermissionDenied


class SendMail(ListView):
    model = Mailing
    template_name = "spam_mailing/send_mail.html"
    context_object_name = "send_mail"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        if self.object.status == "Создана" and self.object.owner == self.request.user:
            try:
                send_mail_list(self)  # Функция в разделе сервисы, отправляет сообщения по рассылке
            except smtplib.SMTPException as error:
                MailingAttempt.objects.create(
                    mailing=self.object, mail_response=error, status="Не успешно", owner=self.request.user
                )
        return self.object


class MailingAttemptView(ListView):
    model = MailingAttempt
    template_name = "spam_mailing/mailing_attempt.html"
    context_object_name = "mailing_attempt"

    def get_queryset(self):
        return MailingAttempt.objects.filter(owner=self.request.user)


class MailingStopView(DetailView):
    model = Mailing
    template_name = "spam_mailing/mailing_stop.html"
    context_object_name = "mailing"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.has_perm("can_stop_mailing"):
            self.object.status = "Завершена"
            self.object.save()
        return self.object


class UserListView(ListView):
    model = CustomUser
    template_name = "spam_mailing/user_list.html"
    context_object_name = "users"

    def get_queryset(self):
        user = self.request.user
        if user.has_perm("users.can_ban_user"):
            return CustomUser.objects.all()
        return PermissionDenied

spam_mailing/templates/spam_mailing/basic_design.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
    <body>
        {% block header %}
        {% endblock %}
        <div class="container ">
            {% block content %}
            {% endblock %}

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        SendMail
                        <small class="d-block mb-3 text-muted">&copy; 2025</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Категории</h5>
                        <ul class="list-unstyled text-small">
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Дополнительно</h5>
                        <ul class="list-unstyled text-small">
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>О нас</h5>
                        <ul class="list-unstyled text-small">
                        </ul>
                    </div>
                </div>
            </footer>
        </div>

        <script src="/static/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

spam_mailing/templates/spam_mailing/home.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">SendMail - это отличный вариант создания кампаний для презентаций ваших продуктов и рекламных
        рассылок</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:send_mail' %}">Запустить рассылки</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img src="media/mailing_service/photo/all_send_mail.jpg" width="270" height="200">
                <h4 class="my-0 font-weight-normal">Рассылки пользователям</h4>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p class="card-title pricing-card-title">У вас: {{ all_mailing.count }} шт.</p>
                {% else %}
                    <p class="card-title pricing-card-title">Всего: {{ all_mailing.count }} шт.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img src="media/mailing_service/photo/active_mailing.jpg" width="250" height="200">
                <h4 class="my-0 font-weight-normal">Активные рассылки</h4>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p class="card-title pricing-card-title">У вас: {{ active_mailing.count}} шт.</p>
                {% else %}
                    <p class="card-title pricing-card-title">Всего: {{ active_mailing.count}} шт.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-6 box-shadow">
            <div class="card-header">
                <img src="media/mailing_service/photo/user_mail.jpg" width="200" height="200">
                <h4 class="my-0 font-weight-normal">Уникальные получатели</h4>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p class="card-title pricing-card-title">У вас: {{ unique_receivers.count }} пользователей.</p>
                {% else %}
                    <p class="card-title pricing-card-title">Всего: {{ unique_receivers.count }} пользователей.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

spam_mailing/templates/spam_mailing/mailing_create.html
receiver_create.html{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель рассылки{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавляем получателя рассылки</h1>
</div>

{% endblock %}

{% block content %}
<div class="card-body">
    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                {% if object %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
            </button>
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:home' %}">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

spam_mailing/templates/spam_mailing/mailing_delete.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Delete{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ message_delete.text_topic }}</h1>
</div>

{% endblock %}

{% block content %}
<form method="post" action="" class="form-floating">
    {% csrf_token %}
    <div class="row text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h1 class="my-0 font-weight-normal">Вы точно хотите удалить рассылку "{{ mailing_delete.text_msg }}" ?</h1>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Подтвердить</button>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:home' %}">Отменить</a>
                </ul>
            </div>
        </div>
    </div>
</form>
{% endblock %}

spam_mailing/templates/spam_mailing/mailing_detail.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Пользователи для отправки сообщений</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="#">Добавить
        рассылку</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Начало рассылки</th>
            <th scope="col">Конец рассылки</th>
            <th scope="col">Текст сообщения</th>
            <th scope="col">Получатели</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ mailing_detail.date_start }}</td>
            <td>{{ mailing_detail.date_end }}</td>
            <td>{{ mailing_detail.text_msg }}</td>
            <td>{{ mailing_detail.receivers_msgs }}</td>
            <td scope="col"><a href="{% url 'spam_mailing:send_mail' %}" class="btn btn-outline-success">Запустить</a></td>
            <td>
                {% if user.is_authenticated %}
                <a href="#" class="text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                    </svg>
                </a>
                <a class="btn btn-close" aria-label="Close"
                   href="#"></a>
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

spam_mailing/templates/spam_mailing/mailing_list.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Пользователи для отправки сообщений</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:mailing_create' %}">Добавить
        рассылку</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Дата начала рассылки</th>
            <th scope="col">Дата конца расслылки</th>
            <th scope="col">Статус</th>
            <th scope="col">Текст сообщения</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for attempt in mailing_list %}
                <td>{{ attempt.date_start }}</td>
                <td>{{ attempt.date_end }}</td>
                <td>{{ attempt.status }}</td>
                <td>{{ attempt.text_msg }}</td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

spam_mailing/templates/spam_mailing/reciever_list.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Пользователи для отправки сообщений</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:receiver_create' %}">Добавить
        получателя</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Email</th>
            <th scope="col">Имя</th>
            <th scope="col">Описание</th>
            <th scope="col">Владелец</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for attempt in receiver_list %}
                <td>{{ attempt.email }}</td>
                <td>{{ attempt.name }}</td>
                <td>{{ attempt.description }}</td>
                <td>{{ attempt.owner }}</td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}