config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("spam_mailing.urls", namespace="spam_mailing")),
    path("users/", include("users.urls", namespace="users")),
]

users/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (EmailConfirmationFailedView, EmailConfirmationSentView, EmailConfirmedView, UserBanView,
                         UserBlock, UserConfirmEmailView, UserCreateView, UserForgotPasswordView,
                         UserPasswordResetConfirmView)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html", form_class=AuthenticationForm), name="login"),
    path("logout/", LogoutView.as_view(next_page="spam_mailing:home"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirmation-sent/", EmailConfirmationSentView.as_view(), name="email_confirmation_sent"),
    path("confirm-email/<str:uidb64>/<str:token>/", UserConfirmEmailView.as_view(), name="confirm_email"),
    # Подтверждение email
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path("confirm-email-failed/", EmailConfirmationFailedView.as_view(), name="email_confirmation_failed"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path("set-new-password/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user_ban", UserBanView.as_view(), name="user_ban"),
    path("user_block/<int:pk>/", UserBlock.as_view(), name="user_block"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.db import models


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    username = None

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [("can_ban_user", "can ban user"), ("can_stop_mailing", "can stop mailing")]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import CustomUser


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email", "password1", "password2")

users/views.py
import os
import secrets

from django.contrib.auth import get_user_model, login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.models import Site
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView

from users.models import CustomUser

from .forms import UserRegisterForm

User = get_user_model()


class UserCreateView(CreateView):
    model = CustomUser
    template_name = "users/user_form.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("spam_mailing:home")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()

        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy("users:confirm_email", kwargs={"uidb64": uid, "token": token})
        current_site = Site.objects.get_current().domain
        send_mail(
            "Подтвердите свой электронный адрес",
            f"Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес "
            f"электронной почты: http://{current_site}{activation_url}",
            os.getenv("EMAIL_HOST_USER"),
            [user.email],
            fail_silently=False,
        )
        return redirect("users:email_confirmation_sent")


class UserConfirmEmailView(View):
    """Класс представления подтверждения почты"""

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect("users:email_confirmed")
        else:
            return redirect("users:email_confirmation_failed")


class EmailConfirmationSentView(TemplateView):
    """Представление письмо отправлено"""

    template_name = "users/email_confirmation_sent.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Письмо активации отправлено"
        return context


class EmailConfirmedView(TemplateView):
    """Подтверждение активации"""

    template_name = "users/email_confirmed.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Ваш электронный адрес активирован"
        return context


class EmailConfirmationFailedView(TemplateView):
    """Подтверждение, что не активирован аккаунт"""

    template_name = "users/email_confirmation_failed.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Ваш электронный адрес не активирован"
        return context


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """

    # form_class = UserForgotPasswordForm
    template_name = "users/user_password_reset.html"
    success_url = reverse_lazy("users:login")
    success_message = "Письмо с инструкцией по восстановлению пароля отправлена на ваш email"
    subject_template_name = "users/password_subject_reset_mail.txt"
    email_template_name = "users/password_reset_mail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Запрос на восстановление пароля"
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """

    # form_class = UserSetNewPasswordForm
    template_name = "users/user_password_set_new.html"
    success_url = reverse_lazy("users:login")
    success_message = "Пароль успешно изменен. Можете авторизоваться на сайте."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Установить новый пароль"
        return context


class UserBanView(ListView):
    model = CustomUser
    template_name = "users/user_ban.html"
    context_object_name = "users"

    def get_queryset(self):
        user = self.request.user

        if user.has_perm("users.can_ban_user"):
            return CustomUser.objects.all()
        return PermissionDenied


class UserBlock(DetailView):
    model = CustomUser
    template_name = "users/users_block.html"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.has_perm("can_ban_user"):
            self.object.is_active = False
            self.object.save()
        return self.object

users/templates/users/email_confirmation_failed.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
</div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'spam_mailing/home.html' %}
{% load my_tags %}
{% block title %}Login{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="card-body">
    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                Войти
            </button>
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:home' %}">Назад</a>
            <a class="px-3 py-3 btn btn-lg btn-block btn-outline" href="{% url 'users:password_reset' %}">Забыли
                        пароль?</a>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_mail.html
{% autoescape off %}
    
    Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

	Перейдите на следующую страницу и выберите новый пароль:
	{% block reset_link %}
	    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	Ваше имя пользователя, если вы забыли: {{ user.get_username }}

	Спасибо за использование нашего сайта!

	The {{ site_name }} team

{% endautoescape %}

users/templates/users/user_ban.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Пользователи для отправки сообщений</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="#">Добавить
        рассылку</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Email</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for attempt in users %}
                <td>{{ attempt.email }}</td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

users/templates/users/user_block.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Пользователи для отправки сообщений</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="#">Добавить
        рассылку</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Пользователь заблокирован.</h4>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'spam_mailing/home.html' %}
{% load my_tags %}
{% block title %}Регистрация{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Регистрация</h1>
</div>

{% endblock %}

{% block content %}
<div class="card-body">
    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                Регистрация
            </button>
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'spam_mailing:home' %}">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title text-center">
            <h4>Запрос на восстановление пароля на сайте</h4>
        </div>
        <form class="text-center" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'spam_mailing/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'spam_mailing/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Установить новый пароль</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
        </form>
    </div>
</div>
{% endblock %}